### ISSUE TITLE
Unexpected name for interface

### ISSUE THREAD

**Issue by cmu-rgrempel** [kubevirt/macvtap-cni#100]
I wanted to follow up on [this comment](https://github.com/kubevirt/macvtap-cni/issues/95#issuecomment-1491376375). I'm experiencing the same problem and can resolve it in the same way, but I'm assuming there's a better way.

**What happened**:

When trying to start a VM using macvtap, something is looking for an interface with a name that matches the name of the multus definition. However, the interface name that exists is in fact `net1`. So, I have name the multus definition `net1` for it to work.

**What you expected to happen**:

Well, I'm not absolutely sure what's supposed to happen, but I guess I'm expecting the interface to be created with a name that matches what will be expected. I'm guessing that there may be some renaming involved somewhere? In fact, if I look at the `dmesg` output on the host, I see this:

```
[418841.802545] net1: renamed from vlan4Mvp46
```

I'm guessing that's part of the problem, but the error message is actually looking for the name of the multus definition, not vlan4Mvp46, so I'm not sure.

**How to reproduce it (as minimally and precisely as possible)**:

Here's the NetworkAttachmentDefinition that fails:

```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bobnet
  namespace: windows
  annotations:
    k8s.v1.cni.cncf.io/resourceName: macvtap.network.kubevirt.io/vlan4
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "bobnet",
      "type": "macvtap"
    }
```

Note this works if I change the name from "bobnet" to "net1". The message I get from virt-handler if I don't change the name to "net1" is this:

```
lstat /proc/3500641/root/sys/class/net/bobnet: no such file or directory
```

So, I think it's looking for an interface named "bobnet", and not finding one, it complains. But, if I change the name to "net1" it works (and everything works).

Here's the relevant part of the VirtualMachine definition:

```
     networks:
      - name: extra
        multus:
          networkName: bobnet
     domain:
       devices:
         interfaces:
         - name: extra
           macvtap: {}
       resources:
         limits:
           macvtap.network.kubevirt.io/vlan4: 1
```

When I change "bobnet" to "net1" in the NAD, I do it here as well, at which point it works.

And here's my macvtap config:

```
DP_MACVTAP_CONF: >-
    [ {
        "name" : "vlan1",
        "lowerDevice" : "vlan1",
        "mode": "bridge",
        "capacity" : 50
     },
     {
        "name" : "vlan4",
        "lowerDevice" : "vlan4",
        "mode": "bridge",
        "capacity" : 50
     },
     {
        "name" : "bond0",
        "lowerDevice" : "bond0",
        "mode": "bridge",
        "capacity" : 50
     } ]
```

**Anything else we need to know?**:

Note that it's still problematic if I leave the name out of the "config" -- it looks as though virt-handler is expecting an interface named according to the name of the NetworkAttachmentDefinition. But, something appears to be re-naming it `net1`, so it only works if that's actually the name of the NetworkAttachmentDefinition. Or, something like that -- I'm not sure how it's supposed to work.

This is on Kubernetes 1.23, Debian 11.

**Comment by cmu-rgrempel** [comment]
I'm trying to figure out what influence I have over the interface name, who's responsible for the renaming, whether it can be prevented, etc. It would be helpful to know what's supposed to happen. For instance:

- In the virt-launcher pod, the macvtap interface is named `net1` -- in fact, `net@if7`. Is that what's expected?
- According to the error message I reported above, virt-handler is looking for an interface named according to the name of the multus `NetworkAttachmentDefinition`. Is that what's expected? Is that how multus would normally name the interface?

Part of my difficulty is that I'm not sure, as between multus, kubevirt and macvtap, who is doing what and who is expecting what. I suppose that the error message I'm seeing is literally from virt-handler, so perhaps this is actually a virt-handler problem?

I noticed that there are some relevant annotations on the virt-launcher pod:

```
    annotations:
      cni.projectcalico.org/containerID: 1a78691093d970853c366f68ac2c93b422a1b41cfe4828dc31d0234c7d3eee08
      cni.projectcalico.org/podIP: 10.244.68.85/32
      cni.projectcalico.org/podIPs: 10.244.68.85/32
      k8s.v1.cni.cncf.io/network-status: |-
        [{
            "name": "k8s-pod-network",
            "ips": [
                "10.244.68.85"
            ],
            "default": true,
            "dns": {}
        },{
            "name": "windows/bobnet",
            "interface": "net1",
            "mac": "7e:e6:42:99:c2:5f",
            "dns": {}
        }]
      k8s.v1.cni.cncf.io/networks: '[{"interface":"net1","name":"bobnet","namespace":"windows"}]'
      k8s.v1.cni.cncf.io/networks-status: |-
        [{
            "name": "k8s-pod-network",
            "ips": [
                "10.244.68.85"
            ],
            "default": true,
            "dns": {}
        },{
            "name": "windows/bobnet",
            "interface": "net1",
            "mac": "7e:e6:42:99:c2:5f",
            "dns": {}
        }]
```

So, whoever made those annotations (presumably multus?) is aware of the name of the NetworkAttachmentDefinition, and aware of the interface name that was ultimately used.

**Comment by maiqueb** [comment]
> I'm trying to figure out what influence I have over the interface name, who's responsible for the renaming, whether it can be prevented, etc. It would be helpful to know what's supposed to happen. For instance:
> 
> * In the virt-launcher pod, the macvtap interface is named `net1` -- in fact, `net@if7`. Is that what's expected?
> * According to the error message I reported above, virt-handler is looking for an interface named according to the name of the multus `NetworkAttachmentDefinition`. Is that what's expected? Is that how multus would normally name the interface?

We (KubeVirt ...) are requesting multus to name the created interface `net1`, as you can see in the pod's network selection elements:
```json
k8s.v1.cni.cncf.io/networks: '[{"interface":"net1","name":"bobnet","namespace":"windows"}]'
```

KubeVirt's virt-controller is templating the virt-launcher pod, and requests this interface.

> 
> Part of my difficulty is that I'm not sure, as between multus, kubevirt and macvtap, who is doing what and who is expecting what. I suppose that the error message I'm seeing is literally from virt-handler, so perhaps this is actually a virt-handler problem?
> 
> I noticed that there are some relevant annotations on the virt-launcher pod:
> 
> ```
>     annotations:
>       cni.projectcalico.org/containerID: 1a78691093d970853c366f68ac2c93b422a1b41cfe4828dc31d0234c7d3eee08
>       cni.projectcalico.org/podIP: 10.244.68.85/32
>       cni.projectcalico.org/podIPs: 10.244.68.85/32
>       k8s.v1.cni.cncf.io/network-status: |-
>         [{
>             "name": "k8s-pod-network",
>             "ips": [
>                 "10.244.68.85"
>             ],
>             "default": true,
>             "dns": {}
>         },{
>             "name": "windows/bobnet",
>             "interface": "net1",
>             "mac": "7e:e6:42:99:c2:5f",
>             "dns": {}
>         }]
>       k8s.v1.cni.cncf.io/networks: '[{"interface":"net1","name":"bobnet","namespace":"windows"}]'
>       k8s.v1.cni.cncf.io/networks-status: |-
>         [{
>             "name": "k8s-pod-network",
>             "ips": [
>                 "10.244.68.85"
>             ],
>             "default": true,
>             "dns": {}
>         },{
>             "name": "windows/bobnet",
>             "interface": "net1",
>             "mac": "7e:e6:42:99:c2:5f",
>             "dns": {}
>         }]
> ```
> 
> So, whoever made those annotations (presumably multus?) is aware of the name of the NetworkAttachmentDefinition, and aware of the interface name that was ultimately used.

No, that's multus API. You request additional networks from multus by using network selection elements, and it reports the pod's status via network-status. More info in the [multus docs](https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/docs/how-to-use.md#run-pod-with-network-annotation).

KubeVirt's virt-controller is the one templating the pod.

**Comment by cmu-rgrempel** [comment]
Ah, thanks, that's helpful.

I guess the part I don't understand then is this: if Kubevirt is deliberately asking multus to name the interface `net1`, then why is virt-handler looking for an interface named `bobnet` (which is the whimsical name I gave the multus NetworkAttachmentDefinition). That is, why do I get this error (preventing the VM from starting) from virt-handler:

```
lstat /proc/3500641/root/sys/class/net/bobnet: no such file or directory
```

... if Kubevirt knows the interface name is going to be `net1`?

**Comment by cmu-rgrempel** [comment]
I found the actual error message from the virt-handler pod's logs -- it looks like this:

```
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance windows/testvm","pos":"vm.go:1474","reason":"lstat /proc/1195600/root/sys/class/net/bobnet: no such file or 
directory","timestamp":"2023-04-19T14:53:34.296066Z"}
```

It's possible that this isn't really a macvtap issue -- it's virt-handler that's looking for something that appears isn't really supposed to exist? The log message gives a filename and line number, so perhaps I'll try to reconstruct from that why it's looking for an interface named `bobnet`.

**Comment by cmu-rgrempel** [comment]
I should note that I'm using Kubevirt 0.59.0. Since this is possibly turning into a Kubevirt investigation more than an macvtap-cni investigation, I should possibly continue this issue in a different repo. In fact, I suppose I should try to reproduce the issue with a different multus plugin -- if I get the same result, then clearly it's a Kubevirt issue and not a macvtap issue.

The code that's generating the error message in the log is this, from https://github.com/kubevirt/kubevirt/blob/v0.59.0/pkg/virt-handler/vm.go#L1467-L1481

```
func (c *VirtualMachineController) Execute() bool {
	key, quit := c.Queue.Get()
	if quit {
		return false
	}
	defer c.Queue.Done(key)
	if err := c.execute(key.(string)); err != nil {
		log.Log.Reason(err).Infof("re-enqueuing VirtualMachineInstance %v", key)
		c.Queue.AddRateLimited(key)
	} else {
		log.Log.V(4).Infof("processed VirtualMachineInstance %v", key)
		c.Queue.Forget(key)
	}
	return true
}
```

So, I guess I'll need to dive into `VirtualMachineController.execute` to see what's really generating the error -- of course, that totally is Kubevirt not macvtap.

**Comment by cmu-rgrempel** [comment]
I'm now pretty confident that my problem is not macvtap-specific. I tried a different multus plugin, and I'm getting the same problem. So, it's (likely) something in my version of Kubevirt, or multus, or their interaction, that's causing the problem. I installed Kubevirt and multus separately (rather than, say, using the hyperconverged operator), so it's possible that I'm using versions that are mismatched in some way. Anyway, I'll try following this up with a focus on those two components instead, and close this issue here.

**Comment by cmu-rgrempel** [comment]
So, I tried downgrading Kubevirt from 0.59.0 to 0.58.1, and the problem went away. So, it looks like, at least in my case, the problem was caused by some change in Kubevirt 0.59.0. So, very clearly not actually related to macvtap.

I'll write up an issue for Kubevirt when I get a chance.
