### ISSUE TITLE
Any plans for arm64 support?

### ISSUE THREAD

**Issue by sunnoy** [kubevirt/macvtap-cni#103]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by maiqueb** [comment]
Not currently. We have no plans (nor knowledge or time to invest on ...) to support ARM releases.

If you're willing to put in the work, to make that happen, we can revisit this decision.

**Comment by caijian76** [comment]
Hope to support arm system
